package com.example.submission;

import java.util.ArrayList;

public class PresidentData {
    public static String[][] data = new String[][]{
            {"Masjid Al-Haram", "Masjid terbesar dan terindah di dunia yang pertama adalah Masjid Al-Haram (Masjidil Haram) di Kota Mekkah, Arab Saudi. Mesjid Al-Haram memang merupakan masjid yang paling utama dan terbesar di dunia ini. Luas masjid ini sendiri tercatat mencapai 4.008.020 meter persegi (990,40 hektar) yang meliputi ruang berdoa outdoor dan indoor. Dengan luas sebesar ini, maka masjid ini akan mampu menampung hingga empat juta jamaah selama musim haji, salah satu ibadah dari rukun Islam yang kelima.", "https://image.cermati.com/f_auto,q_70/fprsdh1scq4jye4aftzl.webp"},
            {"Al-Masjid al-Nabawi", "Masjid terbesar kedua yang ada di Arab Saudi dan di dunia adalah Masjid Nabawi di Madinah. Masjid ini juga memiliki sejarah yang penting bagi umat Islam. Pasalnya masjid yang dibangun oleh Nabi Muhammad SAW ini merupakan masjid kedua yang dimiliki umat Islam setelah Masjidil Haram. Selain itu di dalam komplek masjid ini terdapat makam baginda Nabi Muhammad SAW yang merupakan nabi penutup akhir zaman. Setelah ekspansi pada masa pemerintahan al-Walid I, juga sekarang menggabungkan lokasi tempat peristirahatan terakhir dari Muhammad dan para pemimpin Muslim awal Abu Bakar dan Umar bin Khatab.", "https://image.cermati.com/f_auto,q_70/b4ak6fklshpfzntkvdja.webp"},
            {"Masjid Al-Aqsa", "Setelah dari Arab Saudi kita bergeser ke Palestina atau tepatnya di wilayah kota lama Yerusalem. Di daerah ini ada sebuah masjid agung yang menjadi tempat atau situs suci ketiga bagi umat Islam setelah Masjid Al-Haram dan Masjid Nabawi. Hal ini dikarenakan Masjid yang bisa menampung jamaah hingga 5.000 orang di dalam ruangan ini diyakini sebagai tempat terjadinya peristiwa Isra’ Mi’raj Nabi Muhammad SAW. Peristiwa Isra’ Mi’raj sendiri adalah perjalanan Nabi Muhammad SAW dari Masjidil Haram ke Masjidil Aqsa dan dari Masjidil Aqsa ke ke Sidratul Muntaha. Di dalam komplek masjid ini sendiri terdapat Kubah Batu yang juga disebut sebagai al-Haram ash-Sharif atau \"Suci Noble Sanctuary\".", "https://image.cermati.com/f_auto,q_70/vkbqd4nj5xpokiwuuioa.webp"},
            {"Masjid Imam Reza", "Iran juga memiliki masjid yang besar dan indah. Terletak di wilayah Mashhad, Iran terdapat sebuah Masjid Imam Reza. Dinamakan Masjid Imam Reza karena di dalam masjid ini terdapat sebuah kompleks yang berisi makam Imam Reza, Imam Syiah Imamiyah ke delapan. Dari segi dimensi dan kapasitas masjid ini memang menjadi salah satu masjid yang terbesar di dunia. Bagaimana tidak, dengan total luas area yang mencapai 598.657 meter persegi (6.443.890 kaki), dengan rincian area dalam masjid 267.079 meter persegi serta tujuh halaman yang mengelilingi itu mencakup area seluas 331.578 meter persegi. Dalam komplek masjid ini sendiri terdapat beberapa ruang yaitu Masjid Goharshad, museum, perpustakaan, empat seminari, makam, Universitas Ilmu Islam Razavi, sebuah ruang makan untuk peziarah, ruang doa yang luas, dan bangunan lainnya. Dengan megahnya bangunan masjid ini maka tak ayal bila kompleks masjid ini sering dijadikan pusat pariwisata di Iran.", "https://image.cermati.com/f_auto,q_70/b98vlfnpvhayguwjhmt7.webp"},
            {"Masjid Faisal", "Sebagai salah satu masjid terbesar di Pakistan tentu saja Masjid Faisal sangat dipandang dan diperhatikan. Bahkan saking besarnya, masjid yang terletak di ibu kota nasional Islamabad ini menjadi masjid terbesar di Asia Selatan. Setelah selesai dibangun pada 1986 masjid Faisal ini kemudian dipahami sebagai Masjid Nasional Pakistan dan dinamai almarhum Raja Faisal bin Abdul Aziz dari Arab Saudi, yang mendukung dan membiayai proyek ini.", "https://image.cermati.com/f_auto,q_70/ekk4tfydod3zfeqom2vw.webp"},
            {"Masjid Badshahi", "Masjid berikutnya ini adalah masjid terbesar kedua di Pakistan. Bernama Masjid Badshahi di Lahore mempunyai keindahan, semangat, dan keagungan era Mughal. Dari sini maka Masjid Badshahi ini selalu menjadi daya tarik wisatawan. Masjid yang mampu menampung hingga 10.000 jamaah di ruang utama dan 100.000 jamaah di halaman ini tetap menjadi masjid terbesar kedua di Pakistan dan di Asia Selatan.", "https://image.cermati.com/f_auto,q_70/moucxv2whaggnm83lkb5.webp"},
            {"Masjid Hassan II", "Masjid terbesar dan terindah tidak hanya berada di kawasan Timur Tengah dan Asia, namun di Afrika juga ada sebuah masjid besar dan indah. Masjid ini dinamakan dengan masjid Hassan II. Masjid yang terletak di wilayah Casablanca ini adalah masjid terbesar di negara Maroko dan terbesar ke-7 di dunia. Masjid ini sendiri selesai dibangun oleh Bouygues tahun 1993 dengan perancang bernama Michel Pinseau. Masjid ini sangat menarik, karena selain memiliki menara masjid tertinggi di dunia yaitu 210 meter (689 kaki), masjid ini memiliki pemandangan luar ke Samudera Atlantik yang sangat indah.", "https://image.cermati.com/f_auto,q_70/ybapzdouxtroq4cfizoo.webp"},
            {"Masjid Istiqlal", "Negara kita Indonesia juga memiliki sebuah masjid yang patut dibanggakan. Masjid ini memiliki menara yang tinggi dan indah serta menjadi masjid terbesar se-Asia Tenggara. Masjid yang bernama Masjid Istiqlal ini berlokasi di kota Jakarta dan dibangun untuk memperingati kemerdekaan Indonesia. Nama Istiqlal sendiri berasal dari bahasa Arab yang berarti \"Kemerdekaan\". Masjid yang mampu menampung hingga lebih dari dua ratus ribu jamaah ini mulai dibuka untuk umum pada 22 Februari 1978.", "https://image.cermati.com/f_auto,q_70/lbzknuz83kw7x9j6pojr.webp"},
            {"Masjid-i Jahan-Numa", "Meski memiliki sejarah lahirnya agama Hindu, namun di India jumlah umat muslim terbilang cukup banyak. Dari sini maka muncul beberapa masjid yang besar dan indah. Salah satu mesjid yang besar dan indah di India tersebut adalah masjid i-Jahan-Numa. Berlokasi di kota Delhi, masjid ini bisa menampung jamaah hingga dua puluh lima ribu jamaah. Masjid ini sendiri dibangun pada masa pemerintahan kaisar Mughal Shah Jahan dari tahun 1650 dan selesai pada 1656. Menariknya masjid ini memiliki beberapa peninggalan dalam lemari di gerbang utara, termasuk salinan antik dari Al-Qur'an yang ditulis pada kulit rusa.", "https://image.cermati.com/f_auto,q_70/rifazfirmnlphbivp5ax.webp"},
            {"Baitul Mukarram", "Masjid nasional Bangladesh yaitu Baitul Mukarram juga perlu diperhitungkan sebagai masjid besar dan indah. Masjid yang didirikan pada 1960-an ini memiliki kapasitas 30.000 jamaah. Karena masjid ini terus penuh sesak dengan jamaah terutama pada bulan suci Ramadhan maka pemerintah Bangladesh pun harus melakukan penambahan luas area masjid hingga ke bagian ekstensi masjid. Dari sini maka kapasitas masjid ini pun saat ini telah bertambah kapasitanya menjadi 40.000 jamaah.", "https://image.cermati.com/f_auto,q_70/pqffqyouqisbddn2qopd.webp"},
            {"Masjid Agung Sultan Qaboos", "Masjid terbesar dan terindah di dunia adalah masjid agung Sultan Qaboos di Oman. Masjid yang lahir dari sebuah kompetisi ini mulai dibangun tahun 1995 ini dengan menggunakan konstruksi Bausher. Pembangunan sendiri dilakukan oleh tim Carillion Alawi LLC selama enam tahun empat bulan. Masjid yang dibangun dengan 300.000 ton batu pasir India ini memiliki ruang utama (tempat shalat) dengan dimensi 74,4 x 74,4 meter) dengan kubah pusat naik hingga ketinggian lima puluh meter di atas lantai. Kubah dan menara utama masjid Sultan Qaboos sendiri memiliki ketinggian 90 meter. Selain itu juga terdapat empat menara mengapit dengan tinggi 45,5 meter.", "https://image.cermati.com/f_auto,q_70/yltyzmu79wdv491rjric.webp"}
    };

    public static ArrayList<President> getListData(){
        President president = null;
        ArrayList<President> list = new ArrayList<>();
        for (String[] aData : data) {
            president = new President();
            president.setName(aData[0]);
            president.setRemarks(aData[1]);
            president.setPhoto(aData[2]);

            list.add(president);
        }

        return list;
    }
}
